const cron = require('node-cron');
const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const Order = require('../models/Order');
const Hotel = require('../models/Hotel');

const CANCELLED = ['cancelled', 'CANCELLED'];
const DELIVERED = ['delivered', 'DELIVERED'];

// ─── Email transport ────────────────────────────────────
const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: process.env.SMTP_PORT || 587,
    secure: false,
    auth: {
        user: process.env.SMTP_EMAIL,
        pass: process.env.SMTP_PASSWORD
    }
});

// ─── Generate PDF as buffer ─────────────────────────────
function generateReportPDF(hotel, orders, start, end) {
    return new Promise((resolve, reject) => {
        const chunks = [];
        const doc = new PDFDocument({ margin: 50, size: 'A4' });

        doc.on('data', c => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const delivered = orders.filter(o => DELIVERED.includes(o.status));
        const totalOrders = orders.length;
        const totalRevenue = delivered.reduce((s, o) => s + (o.totalAmount || 0), 0);
        const avgVal = delivered.length ? Math.round(totalRevenue / delivered.length) : 0;

        // Header
        doc.rect(0, 0, doc.page.width, 110).fill('#0f172a');
        doc.fontSize(22).fillColor('#fff').text(hotel.name, 50, 25, { align: 'center' });
        doc.fontSize(11).fillColor('#94a3b8').text('Monthly Business Report  •  FoodHub Now', { align: 'center' });
        doc.fontSize(9).fillColor('#64748b').text(
            `${start.toLocaleDateString('en-IN')} — ${end.toLocaleDateString('en-IN')}  |  Auto-generated`,
            { align: 'center' }
        );

        // Summary
        const bY = 130, bW = 155, bH = 60, gap = 22;
        [
            { l: 'TOTAL ORDERS', v: String(totalOrders), bg: '#eff6ff' },
            { l: 'TOTAL REVENUE', v: `Rs. ${totalRevenue}`, bg: '#f0fdf4' },
            { l: 'AVG ORDER VALUE', v: `Rs. ${avgVal}`, bg: '#faf5ff' },
        ].forEach((b, i) => {
            const x = 50 + i * (bW + gap);
            doc.roundedRect(x, bY, bW, bH, 6).fill(b.bg);
            doc.fontSize(8).fillColor('#64748b').text(b.l, x + 12, bY + 8, { width: bW - 24 });
            doc.fontSize(18).fillColor('#0f172a').text(b.v, x + 12, bY + 24, { width: bW - 24 });
        });

        // Table
        let y = bY + bH + 20;
        doc.rect(50, y, 500, 20).fill('#f1f5f9');
        doc.fontSize(7).fillColor('#475569').font('Helvetica-Bold');
        doc.text('ORDER ID', 55, y + 6); doc.text('DATE', 140, y + 6);
        doc.text('AMOUNT', 300, y + 6); doc.text('STATUS', 420, y + 6);
        y += 25;
        doc.font('Helvetica').fontSize(8).fillColor('#334155');

        for (const o of orders) {
            if (y > 740) { doc.addPage(); y = 50; }
            doc.text(`#${o._id.toString().slice(-6)}`, 55, y);
            doc.text(new Date(o.createdAt).toLocaleDateString('en-IN'), 140, y);
            doc.text(`Rs. ${o.totalAmount}`, 300, y);
            doc.fillColor(DELIVERED.includes(o.status) ? '#16a34a' : '#2563eb').text(o.status.toUpperCase(), 420, y);
            doc.fillColor('#334155');
            y += 18;
        }

        // Footer
        const fY = doc.page.height - 45;
        doc.fontSize(7).fillColor('#94a3b8').text(
            'Generated by FoodHub Now  |  Support: 6375157243  |  anikjain4470@gmail.com',
            50, fY, { align: 'center', width: 500 }
        );

        doc.end();
    });
}

// ─── Send monthly report to one restaurant ──────────────
async function sendMonthlyReport(hotel) {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth() - 1, 1);
    const end = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59, 999);

    const orders = await Order.find({
        hotel: hotel._id,
        createdAt: { $gte: start, $lte: end },
        status: { $nin: CANCELLED }
    }).sort({ createdAt: -1 });

    const delivered = orders.filter(o => DELIVERED.includes(o.status));
    const totalRevenue = delivered.reduce((s, o) => s + (o.totalAmount || 0), 0);

    const pdfBuffer = await generateReportPDF(hotel, orders, start, end);

    const monthName = start.toLocaleString('en-IN', { month: 'long', year: 'numeric' });

    const emailAddress = hotel.email || hotel.ownerEmail;
    if (!emailAddress) {
        console.log(`⚠️  No email for ${hotel.name} — skipping`);
        return { hotel: hotel.name, status: 'skipped', reason: 'no email' };
    }

    const info = await transporter.sendMail({
        from: `"FoodHub Now" <${process.env.SMTP_EMAIL}>`,
        to: emailAddress,
        subject: `Your Monthly FoodHub Now Business Report — ${monthName}`,
        html: `
            <div style="font-family:Arial,sans-serif;max-width:600px;margin:auto">
                <div style="background:#0f172a;color:#fff;padding:30px;text-align:center;border-radius:12px 12px 0 0">
                    <h1 style="margin:0">FoodHub Now</h1>
                    <p style="color:#94a3b8;margin:4px 0 0">Monthly Business Report</p>
                </div>
                <div style="padding:30px;background:#f8fafc;border-radius:0 0 12px 12px">
                    <p>Hi <b>${hotel.name}</b>,</p>
                    <p>Here's your business summary for <b>${monthName}</b>:</p>
                    <table style="width:100%;border-collapse:collapse;margin:20px 0">
                        <tr>
                            <td style="padding:12px;background:#eff6ff;border-radius:8px;text-align:center">
                                <div style="font-size:12px;color:#64748b">Orders</div>
                                <div style="font-size:24px;font-weight:bold">${orders.length}</div>
                            </td>
                            <td style="width:10px"></td>
                            <td style="padding:12px;background:#f0fdf4;border-radius:8px;text-align:center">
                                <div style="font-size:12px;color:#64748b">Revenue</div>
                                <div style="font-size:24px;font-weight:bold">₹${totalRevenue}</div>
                            </td>
                        </tr>
                    </table>
                    <p>Your detailed report is attached as a PDF.</p>
                    <p style="color:#64748b;font-size:12px;margin-top:30px">
                        Need help? Call 6375157243 or email anikjain4470@gmail.com
                    </p>
                </div>
            </div>
        `,
        attachments: [{
            filename: `FoodHubNow_MonthlyReport_${monthName.replace(' ', '_')}.pdf`,
            content: pdfBuffer,
            contentType: 'application/pdf'
        }]
    });

    console.log(`✅ Monthly report sent to ${hotel.name} (${emailAddress}) — ${info.messageId}`);
    return { hotel: hotel.name, status: 'sent', messageId: info.messageId };
}

// ─── CRON: 1st of every month at 9 AM IST ──────────────
function startMonthlyCron() {
    // Runs at 09:00 on the 1st of every month
    cron.schedule('0 9 1 * *', async () => {
        console.log('📊 Starting Monthly Report Job...');

        const hotels = await Hotel.find({ approved: true });
        const results = [];

        for (const hotel of hotels) {
            try {
                const result = await sendMonthlyReport(hotel);
                results.push(result);
            } catch (err) {
                console.error(`❌ Failed for ${hotel.name}:`, err.message);
                // Retry once
                try {
                    console.log(`🔄 Retrying ${hotel.name}...`);
                    const result = await sendMonthlyReport(hotel);
                    results.push(result);
                } catch (retryErr) {
                    console.error(`❌❌ Retry failed for ${hotel.name}:`, retryErr.message);
                    results.push({ hotel: hotel.name, status: 'failed', error: retryErr.message });
                }
            }
        }

        console.log('📊 Monthly Report Job Complete:', JSON.stringify(results, null, 2));
    }, { timezone: 'Asia/Kolkata' });

    console.log('📅 Monthly report cron scheduled (1st of each month, 9 AM IST)');
}

module.exports = { startMonthlyCron, sendMonthlyReport };
